EXP_NAME: EEMF_Net
SEED: 42

DATASET:
  datadir: ./datasets/MVTec
  texture_source_dir: ./datasets/dtd/images
  target: null
  resize:
    - 224 # height
    - 224 # width
  structure_grid_size: 8
  transparency_range:
    - 0.25 # under bound
    - 1. # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 8
  num_workers: 0

MEMORYBANK:
  nb_memory_sample: 30

MODEL:
  feature_extractor_name: resnet18

TRAIN:
  use_tpu: True #False
  device: cpu
  batch_size: 8
  num_training_steps: 1
  l1_weight: 0.6
  focal_weight: 0.4
  focal_alpha: null
  focal_gamma: 4
  focal_smooth: 1e-4
  use_wandb: True

OPTIMIZER:
  lr: 0.01
  weight_decay: 0.00001

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: True

LOG:
  log_interval: 1
  eval_interval: 1

RESULT:
  savedir: ./saved_model
